### ISSUE TITLE
gui spec bug

### ISSUE THREAD

**Issue by rktjmp** [kunzaatko/nord.nvim#1]
https://github.com/kunzaatko/nord.nvim/blob/8eeb8177238f7fd239586e0a24b5b2dc94021a06/lua/nord-vim.lua#L62-L65

These can combine to create invalid rules because you can end up with "gui=NONE," (trailing ,).

```
highlight VimwikiLink guifg=#87BFCF guibg=NONE guisp=NONE gui=NONE, blend=0
highlight! link VimwikiHeaderChar markdownHeadingDelimiter
highlight! link VimwikiHR Keyword
highlight Underline guifg=NONE guibg=NONE guisp=NONE, gui=NONE blend=0
```

**Comment by kunzaatko** [comment]
Do I understand it correctly, that
```lua
...
        underline = cfg.nord_underline == 1 and "underline," or "",
...
```
would solve this?

**Comment by rktjmp** [comment]
Doubt it. `gui =` is going to be a viml bug. You need more smarts in the construction. I would probably create a table and join.

**Comment by kunzaatko** [comment]
I actually have it from the `nord-vim` scheme where it is done the very [same way](https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim)...

They have:
```vim
let s:italic = "italic,"
if g:nord_italic == 0
  let s:italic = ""
endif
```
and as far as I can tell no special handling of this in the `hi` function... @rktjmp They also have it wrong?

**Comment by rktjmp** [comment]
To be clear, this it the bug:

```
gui=NONE, blend=0
        ^ BUG
```

Which makes vim vomit because it thinks blend=0/NONE is part of gui cause of the comma.

It seems that nord never sets guisp (their last key), so the never have anything after their gui settings and the trailing comma is silently ignored by vim.

So I would say they sort of have a non-impactful/iceberg bug there.

You don't get to do that with Lush. Form your gui string correctly.
