### ISSUE TITLE
Diff rules missing gui key

### ISSUE THREAD

**Issue by rktjmp** [kunzaatko/nord.nvim#2]
https://github.com/kunzaatko/nord.nvim/blob/8eeb8177238f7fd239586e0a24b5b2dc94021a06/lua/nord-vim.lua#L282-L301

re: https://github.com/rktjmp/lush.nvim/commit/7103ea77d738ef48c983491b22ae2ca4f797dbbc#r47924319

**Comment by kunzaatko** [comment]
cc0bfe77542b996622a69a2407ec5e58ee4284a3
