### ISSUE TITLE
colourfull branch not updated

### ISSUE THREAD

**Issue by aleksandersumowski** [kunzaatko/nord.nvim#8]
I think the colorful branch is not updated for the recent API changes. This issue is not present in trunk

```Error detected while processing /Users/aleksandersumowski/.vim_plugged/nord.nvim/colors/nord.vim:
line    2:
E5108: Error executing lua ...s/aleksandersumowski/.vim_plugged/lush.nvim/lua/lush.lua:64: Vim(highlight):E418: Illegal value: bold,,
stack traceback:
        [C]: in function 'nvim_command'
        ...s/aleksandersumowski/.vim_plugged/lush.nvim/lua/lush.lua:64: in function 'apply'
        ...s/aleksandersumowski/.vim_plugged/lush.nvim/lua/lush.lua:110: in function <...s/aleksandersumowski/.vim_plugged/lush.nvim/lua/lush.lua:105>
        [string ":lua"]:1: in main chunk```

**Comment by kunzaatko** [comment]
I will look into it right away. I think the problem is that with a missing `require 'nord-palette'` somewhere.

**Comment by kunzaatko** [comment]
Reconsidering, this is probably because the gui spec does not check for trailing commas.

**Comment by kunzaatko** [comment]
@aleksandersumowski Can you, please, check if this fixes the issue? It should. The problem was that on my system, I use `italic`, but you apparently do not, right? So that way it worked in my system and not on your...

**Comment by kunzaatko** [comment]
Moreover, the comma was not trailing on my system, because there was an additional `italic` after `bold` and on yours there was simply `bold,`...

**Comment by aleksandersumowski** [comment]
Seems to work now. Thanks for ultra quick fix!

**Comment by kunzaatko** [comment]
Happy to hear that! Thanks for the catch!
